name: Java Docker Action Demo

on:
  workflow_dispatch:
  
jobs:
  Java-Docker-Action-Demo:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
        
      - name: Checkout Custom Action
        run: |
          git clone https://${{ secrets.PAT }}@github.com/sudarsana-reddy/java-custom-action.git
          
      - name: List cirrent Dir
        run: |
          ls -ltr
                  
      - name: Java Docker Action Demo
        uses: ./java-custom-action
        
