name: Java Docker Action Demo

on:
  workflow_dispatch:
  push:
  
jobs:
  Java-Docker-Action-Demo:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
        
      - name: Checkout Custom Action
        run: |
          git clone https://${{ secrets.PAT }}@github.com/sudarsana-reddy/java-custom-action.git
          
      - name: List cirrent Dir
        run: |
          ls
          cd java-custom-action 
          ls
                  
      - name: Java Docker Action Demo
        uses: ./java-custom-action   
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:  
          path: ./java-custom-action-1.0-SNAPSHOT.jar
           
         
        
