name: pega-trigger-pipeline

on: 
  workflow_dispatch:
     inputs:
       PEGA_PIEPLINE_ID:
        default: "Pipeline-KGX86"
       PEGA_PROD_NAME:
        default: "MyAppbprod"
       PEGA_PROD_VERSION:
        default: "01.01.02"
       PEGA_DEPLOYMENT_WAIT_TIME:
        default: "2"
       WAIT_TIME_INTERVAL:
        default: "1"      

jobs:
  pega-trigger-pipeline:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Custom Action
        run: |
          git clone https://${{ secrets.PAT }}@github.com/sudarsana-reddy/hello-world-javascript-action.git
      - name: Pega Pipeline Trigger
        id: pegaUpdate
        if: always()
        uses: ./hello-world-javascript-action/custom-actions/pega-trigger-workflow
        with:
          PEGA_DM_REST_URL: ${{secrets.PEGA_DM_REST_URL}}
          PEGA_DM_CLIENT_ID: ${{secrets.PEGA_DM_CLIENT_ID}}
          PEGA_DM_CLIENT_SECRET: ${{secrets.PEGA_DM_CLIENT_SECRET}}
          PEGA_PIEPLINE_ID : ${{ inputs.PEGA_PIEPLINE_ID }}
          PEGA_PROD_NAME: ${{ inputs.PEGA_PROD_NAME }}
          PEGA_PROD_VERSION: ${{ inputs.PEGA_PROD_VERSION }}
          PEGA_DEPLOYMENT_WAIT_TIME: ${{ inputs.PEGA_DEPLOYMENT_WAIT_TIME }}
          WAIT_TIME_INTERVAL: ${{ inputs.WAIT_TIME_INTERVAL }}
          
      - name: Send Email Notification
        uses: ./hello-world-javascript-action/custom-actions/email-notification
        with:
          STATUS: ${{ job.status }}
          SMTP_HOST: "smtp.office365.com"
          SMTP_PORT: "587"
          SMTP_USERNAME: "asreddy@live.com"
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          TO: "asreddy@live.com"
          CC: ""
