name: pega-trigger-pipeline

on: 
  workflow_dispatch:
     inputs:
       PEGA_TARGET_APP:
        default: "MyAppA"
       PEGA_PROD_NAME:
        default: "MyAppA_With_MyAppB_Ruleset"
       PEGA_PROD_VERSION:
        default: "01.01.01"
       PEGA_DEPLOYMENT_WAIT_TIME:
        default: "2"
       WAIT_TIME_INTERVAL:
        default: "1"      

jobs:
  pega-trigger-pipeline:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Custom Action
        run: |
          git clone https://${{ secrets.PAT }}@github.com/sudarsana-reddy/hello-world-javascript-action.git
      - name: Pega Pipeline Trigger
        id: pegaUpdate
        uses: ./hello-world-javascript-action/custom-actions/pega-trigger-workflow
        with:
          PEGA_DM_REST_URL: ${{secrets.PEGA_DM_REST_URL}}
          PEGA_DM_CLIENT_ID: ${{secrets.PEGA_DM_CLIENT_ID}}
          PEGA_DM_CLIENT_SECRET: ${{secrets.PEGA_DM_CLIENT_SECRET}}
          PEGA_TARGET_APP : ${{ inputs.PEGA_TARGET_APP }}
          PEGA_PROD_NAME: ${{ inputs.PEGA_PROD_NAME }}
          PEGA_PROD_VERSION: ${{ inputs.PEGA_PROD_VERSION }}
          PEGA_DEPLOYMENT_WAIT_TIME: ${{ inputs.PEGA_DEPLOYMENT_WAIT_TIME }}
          WAIT_TIME_INTERVAL: ${{ inputs.WAIT_TIME_INTERVAL }}
