name: Hello World Custom Action Test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Custom Action
        uses: actions/checkout@v3
      - name: Test Hello World Custom Action
        id: hello
        uses: sudarsana-reddy/hello-world-docker-custom-action@main
        with:
          who-to-greet: "Sudarsan"
          
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
